improve "Open With" functionality after user feedback
bluewaysw/pcgeos pull request #545
Opened 2024-05-07 19:39 UTC by HubertHuckevoll

2024-05-13 20:07 UTC, bluewaysw requested changes

2024-05-13 20:07 UTC, bluewaysw commented on Library/FMTools/OpenWith/openwith.rev
Yes, here for the release, starting with 6.0.0.0 would be consistent.

2024-05-14 13:19 UTC, HubertHuckevoll commented on Tools/build/product/bbxensem/Template/geos.ini
> +}
You are right in that I didn't think of this at all, but in the current german builds, Graphics Viewer is Graphics Viewer, WebBox is WebBox and WebMagick is WebMagick... so, no fixes needed...?

2024-05-14 13:20 UTC, HubertHuckevoll commented on Installed/Library/FMTools/OpenWith/openwith
I 've added this as a recommendation of RainerB, but I don't think I fully understand it's purpose yet ;-)

2024-05-17 20:46 UTC, bluewaysw requested changes
Please remove files that are unused.

2024-05-17 20:46 UTC, bluewaysw commented on Installed/Library/FMTools/OpenWith/openwith
What this file is about?

2024-05-18 20:39 UTC, HubertHuckevoll commented on Installed/Library/FMTools/OpenWith/openwith
File removed.

2024-05-18 20:55 UTC, bluewaysw approved these changes

2024-05-18 20:55 UTC, merged