Fmsound
bluewaysw/pcgeos pull request #658
Opened 2024-10-01 09:03 UTC by rabe-soft

This PR significantly improves the sound quality of the FM instruments. This applies in particular to the “Drums”. The corresponding standard frequencies have also been adjusted. The standard UI sounds (Notify, Warning ..., Library/User/User/userUtils.asm) have been adjusted so that they sound almost exactly the same as before. 
In addition, a C version of the soundFmt.def file has been added.

2024-10-07 16:41 UTC, bluewaysw requested changes
Please keep geode name for existing components unchanged.

2024-10-07 16:41 UTC, bluewaysw commented on Installed/Driver/Sound/SoundBlaster/Makefile
> -GEODE           = sblaster
Changing the geode name is likely not a good idea here? Could we revert this change?

2024-10-07 19:21 UTC, rabe-soft commented
I am also surprised about this because i have only made a new mkmf / pmake depend. I will have a look to see if there is any problem.

2024-10-11 19:21 UTC, rabe-soft commented
There is no problem about this
`GEODE           = sblaster` in the makefile produces
![grafik](https://github.com/user-attachments/assets/044cf5c2-cac8-462b-9026-1392440defc7)
Then typing mkmf. The makefile now contains `GEODE           = soundblaster` and produces the same files:
![grafik](https://github.com/user-attachments/assets/5c80d9f7-96a4-4815-b248-294e95d839f7)

I think, the GEODE statement simply contains the name of the code folder (I have tested this). In this particular case, the geode name is specified in the local.mk file
![grafik](https://github.com/user-attachments/assets/6b2aed63-b890-4f53-b2d9-5d077196538f)

**Because every new mkmf in the future will generate the statement “GEODE = soundblaster”, my recommendation would be to accept this now.**

Off topic: The 8-character geo name is probably one of the reasons why the EC target has no sound.

2024-11-10 12:03 UTC, bluewaysw approved these changes

2024-11-10 12:03 UTC, merged