Dingbats removed hinting !
bluewaysw/pcgeos pull request #751
Opened 2024-12-16 05:38 UTC by nschulux

Dingbads font not displayed correctly , afther test by removing hinting font is OK.

2024-12-26 10:35 UTC, jirkakunze requested changes

2024-12-26 10:35 UTC, jirkakunze commented on FontData/Ttf/dingbats.ttf
![grafik](https://github.com/user-attachments/assets/eb21d4e0-f4a7-4450-910d-4c2a71dd04fe)

In CharMap, some characters have horizontal fragments.

2024-12-26 20:57 UTC, nschulux commented on FontData/Ttf/dingbats.ttf
You see my Screendump has no Faults , but why now ? 
In Windows :
![image](https://github.com/user-attachments/assets/35379f22-e6a0-4338-9da9-0092d18ee770)

Under Geos now: 
![image](https://github.com/user-attachments/assets/373cc78c-7bad-4c03-b687-04e6a950c0c4)

In Write zoomed :
![image](https://github.com/user-attachments/assets/53722aa6-c00b-495f-bcff-7fb3e9417560)

Before it was good !

2024-12-30 15:16 UTC, jirkakunze approved these changes

2024-12-30 16:20 UTC, bluewaysw approved these changes

2024-12-30 16:20 UTC, merged